name: CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: "smohite"
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:

      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "1.9.3"
      
      - name: Terraform Format and Validate
        run: terraform fmt -check terraform-code
      
      - name: Terraform init
        run: terraform -chdir=terraform-code init 

      - name: Terraform plan
        run:
          export exitcode=0 
          terraform -chdir=terraform-code plan -detailed-exitcode -out tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi
      
      - name: Apply
        run: terrafom apply "tfplan"