name: CI
on:
  workflow_dispatch:

permissions:
  contents: write
#  id-token: write
#  packages: read
#  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_OWNER: "MagicTargo"
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:

      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global url."https://oauth2:${{env.GITHUB_TOKEN}}@github.com".insteadOf https://github.com
  
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
          terraform_version: "1.9.3"

      - name: Terraform Format and Validate
        run: terraform fmt -check terraform-code
      
      - name: Terraform init
        run: terraform -chdir=terraform-code init 

      - name: Terraform plan
        run: |
          export exitcode=0 
          terraform -chdir=terraform-code plan -detailed-exitcode -out main.tfplan || export exitcode=$?

          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT

          if [ $exitcode -eq 1 ]; then
            echo Terraform Plan Failed!
            exit 1
          else
            exit 0
          fi
      
      - name: Apply
        run: terraform -chdir=terraform-code apply "main.tfplan"

      - name: Output 
        run: |
          terraform -chdir=terraform-code output 